### ISSUE TITLE
Importing grouper.jar and tarpsy_grouper.jar in same project leads to conflicts.

### ISSUE THREAD

**Issue by panmari** [swissdrg/webgrouper#35]
Since the package & class name match exatly, the order in which the jars are loaded decides, which files are used (see [here](http://stackoverflow.com/questions/19339670/java-two-jars-in-project-with-same-class?rq=1)). This is not much of a problem right now, since the tarpsy grouper is a strict extension of the functionality of the original grouper, so loading only tarpsy.jar suffices. 

But if the two branches diverge more in the future, we will have a huge problem. 

Possible solutions

* Write our own class loader (as mentioned in link)
* Change load path of tarpsy packages
* NEVER let the two branches diverge and port all changes from master to tarpsy branch. Keep only using tarpsy.jar
* Move shared functionality to other project/jar that then both depend on.

I'd like to hear your opinions @tschimbr, @lunas.

**Comment by panmari** [comment]
Btw, I also asked on [SO](http://stackoverflow.com/questions/32003549/conflicting-class-names-imported-from-jars-in-jruby), to no avail.

**Comment by tschimbr** [comment]
I suggest to move all tarpsy code into a new repository. Or remove all grouper code from the tarpsy branch to avoid having a new repo. This depends on how many private repos still are available on Github... Or release the tarpsy grouper as a separate open source project as already implied by Simon.
The tarpsy project would then have the grouper project as an external dependency. Based on the current tarpsy grouper logic this would make sense. The current logic is very different to the grouper logic and not much code is shared. Though if it will be decided to use a more related logic we'd have to reconsider.

**Comment by panmari** [comment]
@tschimbr is there any progress on this? I'd agree that making the tarpsy branch an own project (with it's own namespace) would make most sense. I'll open a new issue on the grouper project.

**Comment by tschimbr** [comment]
I agree as there is indeed not much shared code. Thanks.

**Comment by tschimbr** [comment]
I'll migrate the code as soon as I have some time.

**Comment by panmari** [comment]
thx @tschimbr , that solved it.
